// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	order "KosKita/features/order"

	mock "github.com/stretchr/testify/mock"
)

// OrderServiceInterface is an autogenerated mock type for the OrderServiceInterface type
type OrderServiceInterface struct {
	mock.Mock
}

// CancelOrder provides a mock function with given fields: userId, orderId, orderCore
func (_m *OrderServiceInterface) CancelOrder(userId int, orderId string, orderCore order.OrderCore) error {
	ret := _m.Called(userId, orderId, orderCore)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, order.OrderCore) error); ok {
		r0 = rf(userId, orderId, orderCore)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrders provides a mock function with given fields: userId
func (_m *OrderServiceInterface) GetOrders(userId uint) ([]order.OrderCore, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []order.OrderCore
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]order.OrderCore, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(uint) []order.OrderCore); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.OrderCore)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostOrder provides a mock function with given fields: userId, input
func (_m *OrderServiceInterface) PostOrder(userId uint, input order.OrderCore) (*order.OrderCore, error) {
	ret := _m.Called(userId, input)

	if len(ret) == 0 {
		panic("no return value specified for PostOrder")
	}

	var r0 *order.OrderCore
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, order.OrderCore) (*order.OrderCore, error)); ok {
		return rf(userId, input)
	}
	if rf, ok := ret.Get(0).(func(uint, order.OrderCore) *order.OrderCore); ok {
		r0 = rf(userId, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.OrderCore)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, order.OrderCore) error); ok {
		r1 = rf(userId, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WebhoocksService provides a mock function with given fields: webhoocksReq
func (_m *OrderServiceInterface) WebhoocksService(webhoocksReq order.OrderCore) error {
	ret := _m.Called(webhoocksReq)

	if len(ret) == 0 {
		panic("no return value specified for WebhoocksService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(order.OrderCore) error); ok {
		r0 = rf(webhoocksReq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderServiceInterface creates a new instance of OrderServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderServiceInterface {
	mock := &OrderServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
